In [9]:
import numpy as np

In [18]:
# The column names for this np array ['Apple', 'Beef', 'Eggs', 'Potatoes']
# The row names for this np array ['Carbonhydrates', 'Protien', 'Fat']
a = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2, 104.0, 52.0, 8.0],
              [1.8, 135.0, 99.0, 0.9]
             ])

In [19]:
# TODO: Calculate the sum. Which axis should you use? axis=0? axis=1?  


In [21]:
# Print out the total Calories of ['Apple', 'Beef', 'Eggs', 'Potatoes']
print(np.sum(a, axis=0))

[ 59.  239.  155.4  76.9]


In [22]:
# Print out the total Calories of ['Carbonhydrates', 'Protien', 'Fat']
print(np.sum(a, axis=1))

[128.4 165.2 236.7]


In [ ]:
# TODO: Calculate the ingredient percentage of each food!

In [24]:

print(a*100/np.sum(a, axis=0))

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]
