In [1]:
import numpy as np
import time

In [ ]:
# TODO: Use numpy to create 5 arrays:
# 1 1D vector
# 1 2D array with shape (2, 3)
# 1 2D ones array with shape (2, 3)
# 1 2D zeros array with shape(2, 3)
# 2 2D array with random values

In [25]:
# 1D vector
# Remember to print its shape
vec = np.array([1,2,3])
print(vec)
vec = vec.reshape((1,3))
print(vec.shape)
print('---------------')
new_vec = vec.T
print(new_vec)
print(new_vec.shape)

[1 2 3]
(1, 3)
---------------
[[1]
 [2]
 [3]]
(3, 1)


In [7]:
# 2D array
# Rememebr to print its shape
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [8]:
# 2D ones array
# Remember to print its shape
ones_arr = np.ones((2,3))
print(ones_arr)
print(ones_arr.shape)

[[1. 1. 1.]
 [1. 1. 1.]]
(2, 3)


In [9]:
# 2D zeros array
# Remember to print its shape
zeros_arr = np.zeros((2,3))
print(zeros_arr)
print(zeros_arr.shape)

[[0. 0. 0.]
 [0. 0. 0.]]
(2, 3)


In [10]:
# Element-wise Addition
arr_new = arr + ones_arr
print(arr_new)

[[2. 3. 4.]
 [5. 6. 7.]]


In [13]:
# Element-wise Multiplication
arr_new = arr * zeros_arr
print(arr_new)

[[0. 0. 0.]
 [0. 0. 0.]]


In [15]:
# Dot Product
# arr dot ones_arr
# (2,3)。 (2,3)
arr_new = arr.T.dot(ones_arr)
print(arr_new)
print(arr_new.shape)

[[5. 5. 5.]
 [7. 7. 7.]
 [9. 9. 9.]]
(3, 3)


In [16]:
# Create 2D array with random values of shape (1000000, 1)
rand1 = np.random.rand(1000000,1)
rand2 = np.random.rand(1000000,1)

In [ ]:
# TODO: Use vectorization to calculate the dot product
# call time.time() twice to calculate the total run time 

In [18]:
begin = time.time()
ans = rand1.T.dot(rand2)
finish = time.time()

In [19]:
print('Ans:', ans)
print('Time', finish-begin)

Ans: [[249858.49000224]]
Time 0.017307758331298828


In [ ]:
# TODO: Use for loop to calculate the dot product
# call time.time() twice to calculate the total run time 

In [20]:
start = time.time()
ans = 0
for i in range(rand1.shape[0]):
    ans += rand1[i][0]*rand2[i][0]
end = time.time()

In [22]:
print('Ans:', ans)
print('Time', end-start)

Ans: 249858.49000222588
Time 1.5302791595458984
